-- Generated from meridian-capital-ops/src/mocks by tools/generate-seed.mjs — do not edit by hand.

IF NOT EXISTS (SELECT 1 FROM [ops].[KpiSnapshots])
INSERT INTO [ops].[KpiSnapshots] ([ScreenKey], [MetricKey], [NumericValue], [TextValue])
VALUES
    (N'funds', N'funds', 3, NULL),
    (N'funds', N'investing', 2, NULL),
    (N'funds', N'committed', 2450, NULL),
    (N'funds', N'calledPct', 78, NULL),
    (N'funds', N'calledAmount', 1910, NULL),
    (N'funds', N'legalEntities', 11, NULL),
    (N'investors', N'investors', 48, NULL),
    (N'investors', N'commitments', 2450, NULL),
    (N'investors', N'kycVerifiedPct', 94, NULL),
    (N'investors', N'kycInReview', 3, NULL),
    (N'investors', N'wireOnFilePct', 92, NULL),
    (N'investors', N'wireMissing', 4, NULL),
    (N'users', N'users', 8, NULL),
    (N'users', N'active', 7, NULL),
    (N'users', N'pendingInvites', 1, NULL),
    (N'users', N'roles', 8, NULL),
    (N'integrations', N'connected', 6, NULL),
    (N'integrations', N'warnings', 1, NULL),
    (N'integrations', N'errors', 0, NULL),
    (N'integrations', N'lastSync', NULL, N'09:40'),
    (N'integrations', N'lastSyncAgo', NULL, N'2m ago'),
    (N'drawdowns', N'facilityLimit', 300, NULL),
    (N'drawdowns', N'facilities', 3, NULL),
    (N'drawdowns', N'drawn', 184.05, NULL),
    (N'drawdowns', N'utilisationPct', 61, NULL),
    (N'drawdowns', N'available', 115.95, NULL),
    (N'drawdowns', N'weightedRate', NULL, N'S+2.72%'),
    (N'investor-access', N'portalUsers', 62, NULL),
    (N'investor-access', N'active', 58, NULL),
    (N'investor-access', N'pendingInvites', 3, NULL),
    (N'investor-access', N'investorsWithAccess', NULL, N'44 / 48'),
    (N'investor-access', N'notEnrolled', 4, NULL),
    (N'wires', N'wiresToday', 6, NULL),
    (N'wires', N'settledAmount', 9.26, NULL),
    (N'wires', N'settledCount', 2, NULL),
    (N'wires', N'inFlightAmount', 15.63, NULL),
    (N'wires', N'inFlightCount', 3, NULL),
    (N'wires', N'exceptions', 1, NULL),
    (N'wires', N'asOf', NULL, N'09:41:22'),
    (N'reconciliation', N'matchedPct', 96.2, NULL),
    (N'reconciliation', N'matchedCount', 124, NULL),
    (N'reconciliation', N'totalItems', 129, NULL),
    (N'reconciliation', N'exceptions', 3, NULL),
    (N'reconciliation', N'unmatched', 5, NULL),
    (N'reconciliation', N'amountInBreak', 0.42, NULL),
    (N'reconciliation', N'asOf', NULL, N'Jul 04 close'),
    (N'reconciliation', N'source', NULL, N'Northern Trust feed'),
    (N'reference-data', N'currenciesUpdated', NULL, N'updated 09:40 · SOFR feed'),
    (N'portal-statements', N'totalCount', 34, NULL),
    (N'portal-tax', N'bannerHeadline', NULL, N'2025 K-1s are available.'),
    (N'portal-tax', N'bannerDetail', NULL, N'Estimated availability for 2026: March 2027. You’ll be notified by email.');

